### ISSUE TITLE
Evaluate different folder structures

### ISSUE THREAD

**Issue by terribleplan** [terribleplan/isomorphic-redux-plus#20]
I'm unconvinced that putting everything into app is the right move. Maybe having it as they originally did with app/shared, app/client, and app/server is right. I just don't like putting things into helpers that are not intended to ever be used on the client (Html for server-side specifically), and then having both entry points in the same folder also seems weird.

**Comment by dweedon** [comment]
See https://github.com/terribleplan/isomorphic-redux-plus/pull/24
