### ISSUE TITLE
Clean up our webpack configs

### ISSUE THREAD

**Issue by terribleplan** [terribleplan/isomorphic-redux-plus#21]
There are tons of files in our webpack directory, with probably a bunch of duplicated crap, we should look at cleaning it up somehow.

As a side note we should look at test and prod, and make them as similar as possible, so that tests are as reflective of prod as possible.

**Comment by dweedon** [comment]
I think there is cleanup work to be done, but I am not sure we have too many webpack configs. Webpack does a bunch of stuff. And we need a couple of extra files for dealing with webpack in a universal app. I did a bunch of consolidation already, but I will take another stab at it.

**Comment by dweedon** [comment]
PR submitted: https://github.com/terribleplan/isomorphic-redux-plus/pull/23
